[project]
name = "recipes"
version = "0.0.1"
description = "A bunch of helpful, reusable snippets for my own python usage."


dependencies = [
    "attrs",
]

[project.optional-dependencies]
dev = [
    "ipython", "pytest", "black", "isort", "pylama", "pytest-asyncio"
]

[tools.pyright]

# [tools.pytest.ini_options.pytest]
# asyncio_mode = "auto"