[project]
name = "recipes"
version = "0.0.1"
description = "A bunch of helpful, reusable snippets for my own python usage."


[project.optional-dependencies]
all = ["attrs", "requests"]
attrs = ["attrs"]
requests = ["requests"]
dev = [
    "ipython", "pytest", "black", "isort", "pylama", "pytest-asyncio"
]

[tools.pyright]

# [tools.pytest.ini_options.pytest]
# asyncio_mode = "auto"